# Build NodeJS Express app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/ecosystems/javascript?view=azure-devops
strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.14'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
- pwsh: echo Hello $(imageName)
- pwsh: Write-Host Hello $(imageName)
- powershell: echo Hello $(imageName)
- powershell: Write-Host Hello $(imageName)